### ISSUE TITLE
cloud you tell me how you trans Entity's propertitys to entity_propertity

### ISSUE THREAD

**Issue by 1v1site** [EvisHome/home-assistant#1]
sorry,it's not a issue,just something i can't figure out too long.🥺
is it a plugin to trans or a nodered automations?
help me please.
thanks you anyway
very good project
pretty ui pretty evishome

**Comment by EvisHome** [comment]
Hi, did you figure it out? I am not fully sure if I understood what you mean? Can you open up this a bit?

**Comment by EvisHome** [comment]
I read your issue once more and think I got it, sorry .. I am slow like that :)

So how to have an entity's attribute as a separate entity?

You can do this in your configuration.yaml

example: I take an entity sensor *sensor.unifi_gateway_www* which has an attribute latency, use the template platform to make it a separate entity. Not sure if there are better ways to do this, but that's how I've done it.

```YAML
  - platform: template
    sensors:
      unifi_udmpro_latency_ms:
        value_template: >-
          {{ state_attr('sensor.unifi_gateway_www', 'latency') | float | round(0) }}
        unit_of_measurement: 'ms'
        friendly_name: Internet Latency
```
